baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
theme: "novela"
pygmentsstyle: "novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
